In [1]:
import numpy as np

In [2]:
#建立numpy
data = np.random.randn(2,3)
data

array([[-0.89040635,  1.43125962, -0.3468048 ],
       [ 0.87671551, -0.82794697, -0.0510734 ]])

In [4]:
data * 10

array([[-8.9040635 , 14.31259618, -3.46804802],
       [ 8.76715509, -8.27946971, -0.51073398]])

In [5]:
data + data

array([[-1.7808127 ,  2.86251924, -0.6936096 ],
       [ 1.75343102, -1.65589394, -0.1021468 ]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

In [8]:
data.ndim

2

In [9]:
data.size

6