In [2]:
import numpy as np
arr = np.random.randint(50,101,size=(5,4))
arr

array([[97, 93, 61, 65],
       [63, 65, 61, 91],
       [94, 96, 60, 76],
       [86, 85, 51, 76],
       [82, 83, 70, 74]])

In [3]:
arr.mean()

76.45

In [4]:
arr.mean(axis=0)

array([84.4, 84.4, 60.6, 76.4])

In [5]:
arr.mean(axis=1)

array([79.  , 70.  , 81.5 , 74.5 , 77.25])