In [126]:
import numpy as np

In [127]:
#建立numpy
data = np.random.randn(2,3)
data

array([[-1.12796414,  1.64969439, -0.29251856],
       [ 0.28441248, -1.87317198, -0.45344308]])

In [128]:
data * 10

array([[-11.27964142,  16.49694394,  -2.9251856 ],
       [  2.8441248 , -18.73171977,  -4.53443079]])

In [129]:
data + data

array([[-2.25592828,  3.29938879, -0.58503712],
       [ 0.56882496, -3.74634395, -0.90688616]])

In [130]:
data.shape

(2, 3)

In [131]:
data.dtype

dtype('float64')

In [132]:
data.ndim

2

In [133]:
data.size

6

In [134]:
type(data)

numpy.ndarray

In [135]:
#使用list來建立numpy
data1 = [6, 7.5, 8, 0, 1]
arr1=np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [136]:
arr1.dtype

dtype('float64')

In [137]:
#2維numpy
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [138]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [139]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [140]:
np.empty((2, 3, 2)).size

12

In [141]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [142]:
#ndarray的dtype代表是元素內的值的資料類型

In [143]:
arr1 = np.array([1, 2, 3],dtype=np.float128)
arr1.dtype

dtype('float128')

In [144]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [145]:
arr.astype(np.float128)

array([1., 2., 3., 4., 5.], dtype=float128)

In [146]:
arr = np.array([[1., 2., 3.],[4., 5. , 6.0]])
arr           

array([[1., 2., 3.],
       [4., 5., 6.]])

In [147]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [148]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [149]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [150]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [151]:
arr2 = np.array([[0., 4., 1.],[7., 2. ,12.]])
arr1
arr1.shape

(3,)

In [152]:
arr2
arr.shape

(2, 3)

In [153]:
result=arr2 > arr

In [154]:
result.dtype

dtype('bool')

In [155]:
result

array([[False,  True, False],
       [ True, False,  True]])

In [156]:
#取出值([索引]),取出局部區域(slicing[3:5])

In [157]:
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
#index
arr[5]

7

In [159]:
arr[5:7]

array([7, 8])

In [160]:
arr[5:7] = 12
arr

array([ 2,  3,  4,  5,  6, 12, 12,  9])

In [161]:
arr = np.arange(2,10)
#使用索引或切割,取出的局部值是一個View
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
arr_slice=arr[5:7]
arr_slice

array([7, 8])

In [163]:
arr_slice[1] = 12345
arr

array([    2,     3,     4,     5,     6,     7, 12345,     9])

In [164]:
arr_slice[:] = 64
arr

array([ 2,  3,  4,  5,  6, 64, 64,  9])

In [165]:
#2維
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d.shape
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
arr2d[0]

array([1, 2, 3])

In [167]:
#類似python list的語法
arr2d[0][-2:]

array([2, 3])

In [168]:
#逗號是維度
arr2d[0,1]

2

In [169]:
#: slicing
arr2d[0,-2:]

array([2, 3])

In [170]:
#使用boolean array,過濾
names = np.array(['Bob', 'Joe', 'Will', 'Rob', 'Ali', 'Jen', 'And'])
names

array(['Bob', 'Joe', 'Will', 'Rob', 'Ali', 'Jen', 'And'], dtype='<U4')

In [171]:
fil = np.array([True,False,False,False,False,False,False])
fil

array([ True, False, False, False, False, False, False])

In [172]:
names[fil]

array(['Bob'], dtype='<U4')

In [173]:
names == 'Bob'

array([ True, False, False, False, False, False, False])

In [174]:
names[names=='Bob']

array(['Bob'], dtype='<U4')

In [175]:
names = np.array(['小王','小張','小明','小玲','小李','小曾','小陳'])
names

array(['小王', '小張', '小明', '小玲', '小李', '小曾', '小陳'], dtype='<U2')

In [176]:
scores = np.random.randint(50,101,(7, 5))
scores

array([[63, 66, 81, 71, 67],
       [58, 77, 87, 51, 63],
       [51, 66, 80, 74, 64],
       [99, 63, 78, 53, 76],
       [89, 73, 69, 53, 82],
       [58, 63, 57, 78, 60],
       [70, 85, 98, 69, 76]])

In [177]:
小王=scores[names=='小王']
小王

array([[63, 66, 81, 71, 67]])

In [178]:
小王.sum()

348

In [179]:
小王.mean()

69.6

In [180]:
scores.sum()

2468

In [181]:
scores.mean()

70.51428571428572

In [182]:
小明 = scores[names=='小明']
小明.sum()

335

In [183]:
小明.mean()

67.0

In [184]:
#改變shape
incomes = np.random.randint(1000,4000,28)
a=incomes.reshape((4, 7))
a[0].sum()


19942

In [185]:
a[1].sum()


19094

In [186]:
a[2].sum()

15768

In [187]:
a[3].sum()

15004