In [54]:
#建立ndArray,整個陣列的運算
import numpy as np
arr1 = np.array([1, 2, 3])
type(arr1)

numpy.ndarray

In [55]:
arr1.dtype

dtype('int64')

In [56]:
#實體方法astype(資料料型)
#將array內的元素轉換資料型別
arr2 = arr1.astype(np.float64)
arr2
arr2.dtype

dtype('float64')

In [57]:
#陣列重要的原因在於,數學運算不需使用for loop迴圈
arr = np.array([[1. , 2., 3.],[4., 5., 6.]])
arr.shape
arr.size

6

In [58]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [59]:
#相同size ndarray的運算
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [60]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
#ndarray可以和純值計算
arr = np.array([[1. , 2., 3.],[4., 5., 6.]])
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [62]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [63]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [64]:
#可以使用比較運算子
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [65]:
# 操作範例:數值計算
# 不同size的運算稱為broadcasting(廣播)
# add(), subtract(),multiply
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) #(3, 3)
b = np.array([10,10,10]) #(3)
a.shape
b.shape

(3,)

In [66]:
a.ndim

2

In [67]:
b.ndim

1

In [68]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
b

array([10, 10, 10])

In [70]:
np.add(a,b)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [71]:
np.subtract(a,b)

array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])

In [72]:
np.multiply(a,b)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [73]:
np.divide(a,b)

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [74]:
#ndarray基本索引和分割
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
d=arr[5]
d

5

In [76]:
e=arr[5:8]
e

array([5, 6, 7])

In [77]:
#更改numpy的內容
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [78]:
#使用array的切割 are views
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [80]:
arr_slice[1] = 12345
arr_slice

array([    5, 12345,     7])

In [81]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [83]:
new_slice=arr[5:8].copy()
new_slice[1] = 789
arr
new_slice[1]

789

In [99]:
arr = np.arange(10)
arr
arr.shape



(10,)

In [104]:
arr1 = arr.reshape((2, 5))
arr1
arr1[0,1]

1

In [91]:
arr2 = arr.reshape((1, 10))
arr2

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [100]:
#arr2[0,1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [102]:
arr3 = arr.reshape((1,1,10))
arr3

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [103]:
arr3[0,0,1]

1

In [110]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d
arr2d[2,2]

9

In [109]:
arr1d = np.array([1, 2, 3,4, 5, 6,7, 8, 9])
arr1d
arr1d[8]

9

In [117]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names
names.shape

(7,)

In [114]:
data = np.random.randn(7, 4)
data

array([[ 1.69099388,  0.3903437 ,  0.17476068,  0.17532059],
       [-1.56314422, -0.89556746, -1.06557223,  0.23921853],
       [-0.27029951, -0.61122424, -0.69431453, -1.36744209],
       [-1.47648763,  0.88971016,  1.1551529 ,  1.66701564],
       [ 0.48196576, -0.82587095,  0.3924783 ,  0.38570024],
       [ 1.59081795, -1.25440176,  1.28344144, -1.05763105],
       [ 0.82987558, -0.48371812, -0.69669339, -0.80561016]])

In [115]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [116]:
data[names == 'Bob']

array([[ 1.69099388,  0.3903437 ,  0.17476068,  0.17532059],
       [-1.47648763,  0.88971016,  1.1551529 ,  1.66701564]])

In [118]:
data

array([[ 1.69099388,  0.3903437 ,  0.17476068,  0.17532059],
       [-1.56314422, -0.89556746, -1.06557223,  0.23921853],
       [-0.27029951, -0.61122424, -0.69431453, -1.36744209],
       [-1.47648763,  0.88971016,  1.1551529 ,  1.66701564],
       [ 0.48196576, -0.82587095,  0.3924783 ,  0.38570024],
       [ 1.59081795, -1.25440176,  1.28344144, -1.05763105],
       [ 0.82987558, -0.48371812, -0.69669339, -0.80561016]])

In [121]:
data[data < 0] = 0
data

array([[1.69099388, 0.3903437 , 0.17476068, 0.17532059],
       [0.        , 0.        , 0.        , 0.23921853],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.88971016, 1.1551529 , 1.66701564],
       [0.48196576, 0.        , 0.3924783 , 0.38570024],
       [1.59081795, 0.        , 1.28344144, 0.        ],
       [0.82987558, 0.        , 0.        , 0.        ]])

In [124]:
# ndarray使用於統計
# ndarray實體的方法mean(),sum(),std()
#module的方法mean(), sum(), std()
#std()標準差在計這組數值,離散的程度
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [125]:
arr.mean()

9.5

In [126]:
np.mean(arr)

9.5

In [127]:
arr.sum()

190

In [128]:
arr.std()

5.766281297335398

In [129]:
arr1 = np.array([0, 5, 9, 14])
arr2 = np.array([5, 6, 8, 9])
arr1.mean()

7.0

In [130]:
arr2.mean()

7.0

In [131]:
arr1.std()

5.1478150704935

In [132]:
arr2.std()

1.5811388300841898

In [135]:
arr3 = np.array([1283,495,941,768,881,995,1145])
arr3.mean()
arr3.std()

236.95973997147055

In [136]:
arr = np.random.randn(5, 4)
arr

array([[ 0.36272221, -0.54233696,  0.44803137, -1.15802015],
       [ 1.52971153,  0.73545614, -1.04113515, -0.42185137],
       [ 1.56328762,  1.44158303,  0.78362304, -0.80803664],
       [ 1.70866588,  1.00520516, -1.28529308,  1.20791296],
       [ 0.06056803, -1.31444393,  0.44288436,  0.13514562]])

In [137]:
arr.mean()

0.24268398205533503

In [138]:
arr.mean(axis=1)

array([-0.22240088,  0.20054529,  0.74511426,  0.65912273, -0.16896148])

In [139]:
arr.mean(axis=0)

array([ 1.04499105,  0.26509269, -0.13037789, -0.20896992])

In [140]:
a = np.array([[0, 30,45],[60,75,90]]) 
a

array([[ 0, 30, 45],
       [60, 75, 90]])

In [141]:
a.max()

90

In [142]:
a.max(axis=0)

array([60, 75, 90])

In [143]:
a.max(axis=1)

array([45, 90])

In [147]:
a = np.array([[0, 20,45],[60,75,90]]) 
a.mean()

48.333333333333336

In [149]:
#module function median()
np.median(a)

52.5