In [2]:
#建立ndArray,整個陣列的運算
import numpy as np
arr1 = np.array([1, 2, 3])
type(arr1)

numpy.ndarray

In [3]:
arr1.dtype

dtype('int64')

In [9]:
#實體方法astype(資料料型)
#將array內的元素轉換資料型別
arr2 = arr1.astype(np.float64)
arr2
arr2.dtype

dtype('float64')

In [12]:
#陣列重要的原因在於,數學運算不需使用for loop迴圈
arr = np.array([[1. , 2., 3.],[4., 5., 6.]])
arr.shape
arr.size

6

In [13]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [14]:
#相同size ndarray的運算
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [15]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#ndarray可以和純值計算
arr = np.array([[1. , 2., 3.],[4., 5., 6.]])
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [18]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [19]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [20]:
#可以使用比較運算子
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])