In [2]:
import numpy as np
arr = np.random.randint(50,101,size=(5,4))
arr

array([[97, 93, 61, 65],
       [63, 65, 61, 91],
       [94, 96, 60, 76],
       [86, 85, 51, 76],
       [82, 83, 70, 74]])

In [3]:
arr.mean()

76.45

In [4]:
arr.mean(axis=0)

array([84.4, 84.4, 60.6, 76.4])

In [5]:
arr.mean(axis=1)

array([79.  , 70.  , 81.5 , 74.5 , 77.25])

In [6]:
np.mean(arr)

76.45

In [9]:
arr1 = np.random.randint(5000,10000,size=(7,))
arr1

array([9069, 6257, 5947, 9265, 6160, 9682, 9370])

In [11]:
arr1.cumsum()

array([ 9069, 15326, 21273, 30538, 36698, 46380, 55750])

In [12]:
arr1.max()

9682