In [1]:
#4個實體屬性size,dtype,shape,ndim

import numpy as np
l = [[1, 2, 3],
     [2, 3, 4]]
a = np.array(l)
a.shape

(2, 3)

In [2]:
a.size

6

In [3]:
a.dtype

dtype('int64')

In [4]:
a.ndim

2

In [6]:
n1 = np.array([1, 2, 3],dtype=np.int64)
n1.dtype

dtype('float64')

In [7]:
#建立python亂數
import random as rd
rd.random()

0.5508315389273968

In [11]:
import numpy as np
arr = np.random.randn(2,3)
arr

array([[-0.20385502, -1.11039143, -0.48608955],
       [ 0.69081088, -0.43518256,  0.2920124 ]])

In [12]:
arr * 10

array([[ -2.03855022, -11.10391427,  -4.86089554],
       [  6.90810884,  -4.35182565,   2.92012402]])

In [14]:
arr += arr
arr

array([[-0.81542009, -4.44156571, -1.94435822],
       [ 2.76324354, -1.74073026,  1.16804961]])

In [16]:
arr1 = np.random.rand(2, 3)
arr1

array([[0.43835005, 0.45598406, 0.32753718],
       [0.4369671 , 0.56850891, 0.07131286]])