In [20]:
import numpy as np
arr = np.array([1,3,5, 7, 9])
arr.__class__

numpy.ndarray

In [21]:
#list
a = [1, 3, 5, 7, 9]
a[2:4]

[5, 7]

In [22]:
b = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
b[0]

[1, 3, 5, 7, 9]

In [23]:
b[0][2:4]

[5, 7]

In [26]:
#list
c = [1, 3, 5, 7, 9]
d = [3, 5, 6, 7, 8]
f = []
for i in range(5):
    newValue = c[i] + d[i]
    f.append(newValue)
f

[4, 8, 11, 14, 17]

In [27]:
#ndarray
import numpy as np
c = np.array([1, 3, 5, 7, 9])
d = np.array([3, 5, 6, 7, 8])
print(c+d)

[ 4  8 11 14 17]


In [28]:
#整個陣列內容的運算
c * d

array([ 3, 15, 30, 49, 72])

In [34]:
e = c / d
e

array([0.33333333, 0.6       , 0.83333333, 1.        , 1.125     ])

In [30]:
c + 20

array([21, 23, 25, 27, 29])

In [31]:
#ndarray有個實體的屬性dtype
c.dtype

dtype('int64')

In [33]:
e.dtype

dtype('float64')

In [35]:
#ndarray有個實體的屬性shape
c.shape

(5,)

In [37]:
f = np.array([[1, 3, 5, 7, 9],[2, 4, 6, 8, 10]])
f.shape

(2, 5)