In [12]:
#使用list
a = [1, 3, 5, 7, 9]
b = [[1, 3, 5, 7, 9],[2, 4, 6, 8, 10]]
print(a * 10)
c = [1, 3, 5, 7, 9]
d = [3, 5, 6, 8, 9]
f = []
for i in range(5):
    addValue = c[i] + d[i]
    f.append(addValue)
f

[1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9, 1, 3, 5, 7, 9]


[4, 8, 11, 15, 18]

In [13]:
#ndArray
import numpy as np
c=np.array([1, 3, 5, 7, 9])
c

array([1, 3, 5, 7, 9])

In [14]:
d = np.array([3, 5, 6, 8, 9])
d

array([3, 5, 6, 8, 9])

In [15]:
c + d

array([ 4,  8, 11, 15, 18])

In [17]:
c * 10

array([10, 30, 50, 70, 90])