In [14]:
import numpy as np
arr = np.random.randint(50,101,size=(5,4))
arr.shape

(5, 4)

In [3]:
arr.mean()

76.45

In [4]:
arr.mean(axis=0)

array([84.4, 84.4, 60.6, 76.4])

In [5]:
arr.mean(axis=1)

array([79.  , 70.  , 81.5 , 74.5 , 77.25])

In [6]:
np.mean(arr)

76.45

In [9]:
arr1 = np.random.randint(5000,10000,size=(7,))
arr1

array([9069, 6257, 5947, 9265, 6160, 9682, 9370])

In [11]:
arr1.cumsum()

array([ 9069, 15326, 21273, 30538, 36698, 46380, 55750])

In [12]:
arr1.max()

9682

In [13]:
arr1.min()

5947

In [17]:
arr3 = np.array([[0, 30, 45],[60, 75, 90]]) #(2,3)
arr3.shape
arr3

array([[ 0, 30, 45],
       [60, 75, 90]])

In [19]:
#實體方法沒有median()
#np的function
np.median(arr3)

52.5

In [20]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])
np.median(arr4)

4.0

In [21]:
arr5 = np.array([0, 5, 9, 14])
arr5.mean()

7.0

In [23]:
arr6 = np.array([5, 6, 8, 9])
arr6.mean()

7.0

In [24]:
arr5.std()

5.1478150704935

In [25]:
arr6.std()

1.5811388300841898